# Generated by Django 4.2.8 on 2024-01-02 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_image_alter_profileimage_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='images',
            new_name='image',
        ),
    ]
